# Build with
# docker build --tag=elektrum_api ./
version: "3"
services:
  elektrum_api_container:
    container_name: elektrum_api
    image: elektrum_api
    # command: tail -f /dev/null
    # volumes:
      # - /Users/eriksklotins/My Drive/_BTH/SERT/_Collaborations/Spotify/MarcusHamrin data work/Notebooks:/home/jovyan/work
      # - /Users/eriksklotins/Documents/notebooks:/home/jovyan/notebooks
    ports:
      - 5001:5000
    restart: unless-stopped
    # network_mode: "host"
